# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20160519_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
